### ISSUE TITLE
Format of Radio URL

### ISSUE THREAD

**Issue by samsonrosen** [petro-kushchak/homebridge-homepod-radio#1]
Hi! I'm so so excited to try this. I'm having issues with atvplayer on my pi - I get 'Illegal Execution'. But I'm just trying some steps here to [resolve.](https://pyatv.dev/support/faq/#when-using-pyatv-on-a-raspberry-pi-eg-running-atvremote-i-get-illegal-instruction-how-do-i-fix-that).

I am going to be broadcasting BBC Radio 6 Music to my HomePod Mini. Do I need to use a static IP address and can you suggest an example URL? There's lots of different formats available online.

Thanks,

Sam

**Comment by petro-kushchak** [comment]
Hi! It runs pretty well on my  **Raspberry Pi 4 Model B Rev 1.4** with Homebridge image **Homebridge Raspbian v1.0.24**. I did not have any issues with installing/running pyatv - so you might try similar setup...

Regarding URLs for BBC radio, any of stream URLs from here should work fine(checked with BBC Radio 6 Music http://stream.live.vc.bbcmedia.co.uk/bbc_6music):
https://gist.github.com/bpsib/67089b959e4fa898af69fea59ad74bc3

**Comment by samsonrosen** [comment]
Cool, thanks for that. I’ll try a couple more things from the issue I raised with PYATV. Very weird because I’m also running the same image and followed your instructions. 

I’m using an iOS shortcut with the BBC Sounds app at the moment but I hate the fact that I need to airplay from my phone to get radio to the HomePod mini in my bedroom. So this plugin will be fab once I get it working!

Regarding the identifier you use a MAC address in your config but the readme says to use an IP address.

**Comment by samsonrosen** [comment]
So I had a bit of a play and it looks like I have to run atvremote -scan with sudo? I think it's because I used sudo to install pyatv which isn't actually what your instructions say.

Do you think it's problematic to your plugin to need sudo to run the atvremote portion?

**Comment by petro-kushchak** [comment]
Homebridge plugin should not require sudo... Make sure you create symlink to atvremote with proper path - in my case I've installed pyatv under "pi" user so symlink points to /home/pi/.local/bin/atvremote

My /user/local/bin content:
```
pi@homebridge:~ $ ls -la /usr/local/bin/
total 93044
drwxr-xr-x  2 root root     4096 Jan  5 17:00 .
drwxr-xr-x 10 root root     4096 Sep 23 20:11 ..
lrwxrwxrwx  1 root root       29 Jan  5 17:00 atvremote -> /home/pi/.local/bin/atvremote
-rwxr-xr-x  1 root root 27004980 Sep  2  2020 ffmpeg
```


>>Regarding the identifier you use a MAC address in your config but the readme says to use an IP address.

Thanks, updated readme :)

**Comment by samsonrosen** [comment]
Thanks for the readme updates - I couldn’t get my pi to work with pyatv. Probably a permissions thing! I have an instance of homebridge running on a Mac server so I installed it on that which works! I look forward to more updates as I still cannot believe HomePods can’t play BBC radio independently. 

Are you able to add into the code a starting volume? It looks like atvremote does support it that parameter even if home in 15.2 doesn’t!

**Comment by petro-kushchak** [comment]
Just pushed 1.1.7 with starting volume, try it out! :)
