### ISSUE TITLE
local admin account

### ISSUE THREAD

**Issue by halandala** [petro-kushchak/homebridge-homepod-radio#12]
Hello, @petro-kushchak 
thanks for this amazing work. I'm trying to install, but i have some issues with pre-requisites. It asks for a local admin password, and even if i put all the password in the world...it doesn't recognize it and i can't install it.
It's not an issue it's my first day using those and it's hard to understand, so it will be great if you can help.

bash-4.4$ sudo apt-get install ffmpeg

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

Password: 
sudo: a password is required

I tried to use NAS password, HB password, it doesnt work. On SSH password is recognized.
If you can give a hint...it will be great:D

thank you!

**Comment by petro-kushchak** [comment]
Hi - for standard Raspberry Pi image try user "pi" and password "raspberry"

**Comment by halandala** [comment]
seems that i found out why is not working - https://github.com/oznu/homebridge-syno-spk/issues/61 

What is not clear with me is how to install pre-requisite using ssh. Can you help on this one?

Thank you!

**Comment by petro-kushchak** [comment]
Hi, looks like you should try to follow this guide: https://kb.synology.com/en-us/DSM/tutorial/How_to_login_to_DSM_with_root_permission_via_SSH_Telnet
