### ISSUE TITLE
Unable to stream normal mp3 files from URL

### ISSUE THREAD

**Issue by ahm322** [petro-kushchak/homebridge-homepod-radio#17]
when I put a direct link to an mp3 file the HomePod mini keeps repeating the first few seconds three times before crashing. Streaming radio like BBC works fine.
I tried creating my own m3u playlist with the mp3 file in the list but it didn't work.

Any simple solution to play remote mp3 files providing the URL?

P.S using the following command directly in the Terminal works fine
```
ffmpeg -i <streamUrl> -f mp3 - | atvremote --id <homepodId> stream_file=-
```

**Comment by petro-kushchak** [comment]
Hi, at the moment plugin supports playback for local mp3, I planned to add mp3 url support as well - will add it in the one of future releases.

From other side weird that playback of mp3 as radio fails, I didn't test this scenario - probably there is some bug (will check it out once get time)
