### ISSUE TITLE
Newbie - Just won't play

### ISSUE THREAD

**Issue by NicBetts** [petro-kushchak/homebridge-homepod-radio#22]
Config below - I'm blanked the last 2 parts of the homepodid for safety.
Manually added the items to Home and see them, status stopped,  when I try and start them all I see in Homebridge logs is....

[13/08/2022, 20:48:56] [HomepodRadioPlatform] [BBC - Radio 2] Triggered GET CurrentMediaState: 2

and nothing else.

HELP!

Config.
{
            "homepodId": "4C:20:B8:DB:XX:XX",
            "httpPort": 7654,
            "verboseModel": true,
            "volumeControl": false,
            "mediaPath": "/home/pi/media",
            "radios": [
                {
                    "name": "BBC - Radio 1",
                    "radioUrl": "http://stream.live.vc.bbcmedia.co.uk/bbc_radio_one",
                    "volume": 25,
                    "autoResume": false
                },
                {
                    "name": "BBC - Radio 2",
                    "radioUrl": "http://stream.live.vc.bbcmedia.co.uk/bbc_radio_two",
                    "volume": 25,
                    "autoResume": false
                }
            ],
            "platform": "HomepodRadioPlatform"
        }

**Comment by petro-kushchak** [comment]
Hi, do you have pyatv installed?

Try to run from your homebridge server:

ffmpeg -i <streamUrl> -f mp3 - | atvremote --id <homepodId> stream_file=-

**Comment by NicBetts** [comment]
Yes I have pyatv installed.
I tried Is this helpful?
(blanked out end of id again)

```
$ ffmpeg -i -f mp3 - | atvremote --id 4C20B8DBXXX play_url=http://stream.live.vc.bbcmedia.co.uk/bbc_radio_two

ffmpeg version 4.2.git-47773f7 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 6.3.0 (Raspbian 6.3.0-18+rpi1+deb9u1) 20170516
  configuration: --pkgconfigdir=/build/workspace/lib/pkgconfig --prefix=/build/workspace --pkg-config-flags=--static --extra-cflags=-I/build/workspace/include --extra-ldflags=-L/build/workspace/lib --extra-libs='-lpthread -lm' --enable-static --disable-debug --disable-shared --disable-ffplay --disable-doc --enable-openssl --enable-gpl --enable-version3 --enable-nonfree --enable-pthreads --enable-libvpx --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libx264 --enable-runtime-cpudetect --enable-libfdk-aac --enable-avfilter --enable-libopencore_amrwb --enable-libopencore_amrnb --enable-filters --enable-decoder=h264 --enable-network --enable-protocol=tcp --enable-demuxer=rtsp --enable-omx-rpi --enable-mmal
  libavutil      56. 40.100 / 56. 40.100
  libavcodec     58. 68.102 / 58. 68.102
  libavformat    58. 38.100 / 58. 38.100
  libavdevice    58.  9.103 / 58.  9.103
  libavfilter     7. 75.100 /  7. 75.100
  libswscale      5.  6.100 /  5.  6.100
  libswresample   3.  6.100 /  3.  6.100
  libpostproc    55.  6.100 / 55.  6.100
-f: No such file or directory
2022-08-14 17:57:47 ERROR [pyatv.scripts.atvremote]: Command 'play_url' is not supported by device
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/pyatv/scripts/atvremote.py", line 683, in _exec_command
    value = await tmp(*args)
  File "/home/pi/.local/lib/python3.7/site-packages/pyatv/core/facade.py", line 382, in play_url
    raise exceptions.NotSupportedError("play_url is not supported")
pyatv.exceptions.NotSupportedError: play_url is not supported

```

**Comment by petro-kushchak** [comment]
Looks like GitHub filtered out parameters for the previous command, can you try this command:

`ffmpeg -i http://stream.live.vc.bbcmedia.co.uk/bbc_radio_two -f mp3 - | atvremote --id 4C20B8DBXXX stream_file=-`

Also which version of iOS you are using? I'm currently have problem with starting playback on iOS 16 beta (so I use Siri Shortcut as workaround)

**Comment by NicBetts** [comment]
That worked and yep iOS 16 Developer Beta 5.
I'll try the shortcut approach you mention.
Key is that I know the install is correct - thank you!
