### ISSUE TITLE
Homebridge Crashing

### ISSUE THREAD

**Issue by samsonrosen** [petro-kushchak/homebridge-homepod-radio#24]
Hello, 

I’m getting the following error from my Mac which streams to my HomePod Mini. I’ve tried to make sure I’m running the latest pyatv and HomePod-radio plugin. It’s intermittent. I trigger the radio through a ‘morning scene’ so a scene starts the radio alongside some other commands. It doesn’t crash every morning but feel like once a week?

Let me know if you need version numbers (and how I can grab them I always forget how). Happy to do whatever testing. I love this plugin so much.

```
05/10/2022, 08:00:01] [HomepodRadioPlatform] [BBC - Radio 6] Started streaming http://stream.live.vc.bbcmedia.co.uk/bbc_6music
[05/10/2022, 08:00:12] Error: Command failed: atvremote --id E02B9691AE2C title

    at ChildProcess.exithandler (node:child_process:397:12)
    at ChildProcess.emit (node:events:390:28)
    at maybeClose (node:internal/child_process:1062:16)
    at Socket.<anonymous> (node:internal/child_process:448:11)
    at Socket.emit (node:events:390:28)
    at Pipe.<anonymous> (node:net:687:12)
[05/10/2022, 08:00:12] Got SIGTERM, shutting down Homebridge...
```

```
"platform": "HomepodRadioPlatform",
    "serialNumber": "REMOVED",
    "homepodId": "REMOVED",
    "radios": [
        {
            "name": "BBC - Radio 6",
            "trackName": "BBC - Radio 6",
            "radioUrl": "http://stream.live.vc.bbcmedia.co.uk/bbc_6music",
            "autoResume": false
        }
    ]
},
      { 
```

**Comment by petro-kushchak** [comment]
Hi, I've noticed this as well with older implementation - my Raspberry Pi was running out of memory in a week or so.

I've re-implemented the way plugin streams audio to HomePod, "beta" version runs for a month already, and its pretty stable in my setup.

Try out this version: **v1.2.15-beta.0**. It also allows to add "switch" accessory, so you can turn on/off radio

**Comment by samsonrosen** [comment]
Hey! How can I check what version I’m now running? And how do you mean a switch accessory? What does that allow me to do?

**Comment by petro-kushchak** [comment]
Hi, 

In Homebridge UI, select plugins and then click on wrench icon:

<img width="976" alt="Screenshot 2022-10-17 at 14 54 37" src="https://user-images.githubusercontent.com/20168120/196171179-c468f711-b263-4853-ac93-f0236e0705bf.png">


This beta allows to add "radio switch" as separate **switch** accessory which workarounds current Home App limitation with starting/stopping radio

**Comment by samsonrosen** [comment]
Ah I run this from my Mac so I do everything via command line still! I’ve had it running before configUX was popular so I never got round to installing it over the top.Sent from my iPhoneOn 17 Oct 2022, at 12:59, Petro ***@***.***> wrote:﻿
Hi,
In Homebridge UI, select plugins and then click on wrench icon:

This beta allows to add "radio switch" as separate switch accessory which workarounds current Home App limitation with starting/stopping radio

**Comment by petro-kushchak** [comment]
Oh, ok - not sure how you installed it previously, try to run:

npm install -g @petro-kushchak/homebridge-homepod-radio v1.2.15-beta.0

**Comment by samsonrosen** [comment]
Hey! I actually committed a bit of time to it and stuck config UI on there so I can now visually see that I’m running the beta!

The switch toggle is excellent. Question though (as someone who also uses BBC Radio streams) - do you have any tips for the URL for Artwork / Meta Data? I’m only using this for BBC 6 Music?
