### ISSUE TITLE
Speaker/Radio button is grey

### ISSUE THREAD

**Issue by leendersf** [petro-kushchak/homebridge-homepod-radio#28]
Hello,

When I use this command from the terminal it works:
ffmpeg -i http://stream.live.vc.bbcmedia.co.uk/bbc_radio_one -f mp3 - | atvremote --id 58D34903CB0D stream_file=-

But in Homekit the radio button is greyed, not playing/stopped and I cannot get it to play radio. Am I doing something wrong?

atvremote scan gives me:

Scan Results
========================================
       Name: Keuken
   Model/SW: HomePod Mini, tvOS 16.3
    Address: 192.168.68.77
        MAC: 58:D3:49:03:CB:0D
 Deep Sleep: False
Identifiers:
 - 58:D3:49:03:CB:0D
 - 58D34903CB0D
Services:
 - Protocol: Companion, Port: 49153, Credentials: None, Requires Password: False, Password: None, Pairing: Unsupported
 - Protocol: AirPlay, Port: 7000, Credentials: None, Requires Password: False, Password: None, Pairing: NotNeeded
 - Protocol: RAOP, Port: 7000, Credentials: None, Requires Password: False, Password: None, Pairing: NotNeeded

       Name: Woonkamer (3)
   Model/SW: Apple TV 4K, tvOS 16.2
    Address: 192.168.68.52
        MAC: 64:D2:C4:A8:77:BA
 Deep Sleep: False
Identifiers:
 - 64:D2:C4:A8:77:BA
 - 64D2C4A877BA
Services:
 - Protocol: Companion, Port: 49153, Credentials: None, Requires Password: False, Password: None, Pairing: Mandatory
 - Protocol: AirPlay, Port: 7000, Credentials: None, Requires Password: False, Password: None, Pairing: Mandatory
 - Protocol: RAOP, Port: 7000, Credentials: None, Requires Password: False, Password: None, Pairing: Mandatory

       Name: Woonkamer (2)
   Model/SW: HomePod Mini, tvOS 16.3
    Address: 192.168.68.76
        MAC: E0:2B:96:AE:ED:73
 Deep Sleep: False
Identifiers:
 - E0:2B:96:AE:ED:73
 - E02B96AEED73
Services:
 - Protocol: Companion, Port: 49153, Credentials: None, Requires Password: False, Password: None, Pairing: Unsupported
 - Protocol: AirPlay, Port: 7000, Credentials: None, Requires Password: False, Password: None, Pairing: NotNeeded
 - Protocol: RAOP, Port: 7000, Credentials: None, Requires Password: False, Password: None, Pairing: NotNeeded

       Name: Woonkamer
   Model/SW: HomePod Mini, tvOS 16.3
    Address: 192.168.68.75
        MAC: F4:34:F0:51:C4:A9
 Deep Sleep: False
Identifiers:
 - F4:34:F0:51:C4:A9
 - F434F051C4A9
Services:
 - Protocol: Companion, Port: 49156, Credentials: None, Requires Password: False, Password: None, Pairing: Unsupported
 - Protocol: AirPlay, Port: 7000, Credentials: None, Requires Password: False, Password: None, Pairing: NotNeeded
 - Protocol: RAOP, Port: 7000, Credentials: None, Requires Password: False, Password: None, Pairing: NotNeeded

       Name: Sportkamer
   Model/SW: Apple TV 3, ATV SW 8.4.4
    Address: 192.168.68.65
        MAC: 9C:20:7B:D7:C4:9A
 Deep Sleep: False
Identifiers:
 - 9C:20:7B:D7:C4:9A
 - 1A5A332FF293FCDD
 - 9C207BD7C49A
Services:
 - Protocol: AirPlay, Port: 7000, Credentials: None, Requires Password: False, Password: None, Pairing: NotNeeded
 - Protocol: DMAP, Port: 3689, Credentials: 00000000-4f94-e287-f730-519933644496, Requires Password: False, Password: None, Pairing: Optional
 - Protocol: RAOP, Port: 7000, Credentials: None, Requires Password: False, Password: None, Pairing: NotNeeded

       Name: Kamer Mex
   Model/SW: Apple TV 4K, tvOS 16.1
    Address: 192.168.68.55
        MAC: 50:DE:06:87:E9:1C
 Deep Sleep: False
Identifiers:
 - 50:DE:06:87:E9:1C
 - 50DE0687E91C
Services:
 - Protocol: Companion, Port: 49153, Credentials: None, Requires Password: False, Password: None, Pairing: Mandatory
 - Protocol: AirPlay, Port: 7000, Credentials: None, Requires Password: False, Password: None, Pairing: Mandatory
 - Protocol: RAOP, Port: 7000, Credentials: None, Requires Password: False, Password: None, Pairing: Mandatory

**Comment by petro-kushchak** [comment]
Hi, in iOS 16 Apple disabled ability to start/stop radio from speaker.

Try out this version: @petro-kushchak/homebridge-homepod-radio v1.2.16-beta.5:
- It has re-implemented the way plugin streams audio to HomePod ("beta" version runs for a couple of months already, and its pretty stable in my setup)
- It also allows to add "switch" accessory, so you can turn on/off radio

**Comment by leendersf** [comment]
Thank you for the reaction: but how can I install it? I tried "sudo npm install -g git+https://github.com/petro-kushchak/homebridge-homepod-radio v1.2.16-beta.5" but there is only 404.

**Comment by leendersf** [comment]
Tnx! I installed it but the speaker says stopped and I cannot control it from Homekit. The switch doesn't do anything. Only this command in terminal seems to work: 
ffmpeg -i http://stream.live.vc.bbcmedia.co.uk/bbc_radio_one -f mp3 - | atvremote --id 58D34903CB0D stream_file=-

The Homepod plays radio but the speaker button doesn't display this..

**Comment by petro-kushchak** [comment]
Could you share plugin configuration and logs?

**Comment by leendersf** [comment]
Yes:
configuration ->

     {
            "homepodId": "58:D3:49:03:CB:0D",
            "httpPort": 7654,
            "verboseMode": true,
            "volumeControl": false,
            "radios": [
                {
                    "name": "Qmusic non stop",
                    "radioUrl": "https://stream.qmusic.nl/qmusic/aachigh",
                    "onSwitch": true,
                    "autoResume": true,
                    "artworkUrl": "https://qmusic.nl/assets/qmusic-a1d81a5f88375b3c5507cbc0b064ce1fc8778a076a245bddfd4f2a3e2417c330.png"
                }
            ],
            "platform": "HomepodRadioPlatform",
            "_bridge": {
                "username": "0E:4E:2E:5B:45:F1",
                "port": 59365
            }
        }
    ],

Debug:

[15-1-2023 20:23:14] Qmusic non stop switch 3E2C is running on port 39959.
[15-1-2023 20:23:14] Please add [Qmusic non stop switch 3E2C] manually in Home app. Setup Code: 171-42-646
[15-1-2023 20:23:15] [@petro-kushchak/homebridge-homepod-radio] [Qmusic non stop] state: null
[15-1-2023 20:23:16] [@petro-kushchak/homebridge-homepod-radio] [Qmusic non stop] Triggered GET CurrentMediaState: 2
[15-1-2023 20:23:16] [@petro-kushchak/homebridge-homepod-radio] [Qmusic non stop Switch] GET ON
[15-1-2023 20:23:21] [@petro-kushchak/homebridge-homepod-radio] [Qmusic non stop Switch] SET ON: true
[15-1-2023 20:23:21] [@petro-kushchak/homebridge-homepod-radio] [Qmusic non stop] Started hearbeat 453
[15-1-2023 20:23:21] [@petro-kushchak/homebridge-homepod-radio] [Qmusic non stop] spawn streaming: 6394
[15-1-2023 20:23:21] [@petro-kushchak/homebridge-homepod-radio] [Qmusic non stop] Started streaming https://stream.qmusic.nl/qmusic/aachigh
[15-1-2023 20:23:21] [@petro-kushchak/homebridge-homepod-radio] [Qmusic non stop] streaming data: Traceback (most recent call last):
  File "/var/lib/homebridge/node_modules/@petro-kushchak/homebridge-homepod-radio/dist/stream.py", line 20, in <module>

[15-1-2023 20:23:21] [@petro-kushchak/homebridge-homepod-radio] [Qmusic non stop] Playback heartbeat, source: streaming
[15-1-2023 20:23:21] [@petro-kushchak/homebridge-homepod-radio] [Qmusic non stop] streaming data:     import pyatv
ModuleNotFoundError: No module named 'pyatv'

[15-1-2023 20:23:21] [@petro-kushchak/homebridge-homepod-radio] [Qmusic non stop] Playback heartbeat, source: streaming
[15-1-2023 20:23:21] [@petro-kushchak/homebridge-homepod-radio] [Qmusic non stop] streaming exit: code 1 signal null
[15-1-2023 20:23:21] [@petro-kushchak/homebridge-homepod-radio] [Qmusic non stop] Killing process: streaming: 6394
[15-1-2023 20:23:21] [@petro-kushchak/homebridge-homepod-radio] [Qmusic non stop] Cleared hearbeat 453 - stop requested
[15-1-2023 20:23:21] [@petro-kushchak/homebridge-homepod-radio] [Qmusic non stop] Error while trying to stop: Error: Command failed: kill -9 6394
/bin/sh: 1: kill: No such process

Thank you!

**Comment by petro-kushchak** [comment]
Hmm - looks like there is some issue with `pyatv` module in your system:

File "/var/lib/homebridge/node_modules/@petro-kushchak/homebridge-homepod-radio/dist/stream.py", line 20, in
 import pyatv ModuleNotFoundError: No module named 'pyatv'

 
This might be related to versions of the python, haven't seen it in my setup. Could you try to run this command:

python3 /var/lib/homebridge/node_modules/@petro-kushchak/homebridge-homepod-radio/dist/stream.py --id 58D34903CB0D --title Radio --album Radio --stream_url  https://stream.qmusic.nl/qmusic/aachigh  --stream_timeout 25 --stream_metadata -1 stream_artwork https://qmusic.nl/assets/qmusic-a1d81a5f88375b3c5507cbc0b064ce1fc8778a076a245bddfd4f2a3e2417c330.png --verbose

**Comment by leendersf** [comment]
It works!! I had to install 'pyatv' in the Homebridge terminal! Great!!! Thank you very much!

**Comment by singalen** [comment]
Just had the same issue, I initially installed `pyatv` from `ssh`. Perhaps the instruction can be clarified.

**Comment by leendersf** [comment]
But it worked for months. Only with this update it broke.
