### ISSUE TITLE
Radio stream frequently interupted with error "ffmpeg pipe error: Error: write EPIPE"

### ISSUE THREAD

**Issue by tomasfearon** [petro-kushchak/homebridge-homepod-radio#29]
## Version Information

- homebridge-homepod-radio v1.1.41
- MacOS 13.1 (22C65)
- Node.js v18.13.0
- ffmpeg 5.1.2
- pyatv 0.10.3
- Python 3.10.9

## Radio Streams Tested

- https://p4.p4groupaudio.com/P04_AM
- http://a.files.bbci.co.uk/media/live/manifesto/audio/simulcast/hls/nonuk/sbr_low/ak/bbc_radio_fourfm.m3u8

## Expected Behaviour

Radio stations stream with minimal interruptions and restarts

## Observed Behaviour

Multiple interruptions and restarts per hour, approximately every 3 minutes. The Homebridge log displays the following error message:
`ffmpeg pipe error: Error: write EPIPE`

The behaviour is not observed when initiating the stream via the command line using:
`ffmpeg -i <streamUrl> -f mp3 - | atvremote --id <homepodId> stream_file=- `
The stream plays without issue for multiple hours with the above command. 

### Updating to latest homebridge-homepod-radio v1.2.16-beta.5 
Crashes Homebridge every time a stream is started. It does start a stream successfully, and doesn't seem to drop out, but it's not possible to stop the stream unless you restart Homebridge or play other media on the Homepod. The following error is printed to the log when it crashes:

```
Error: This callback function has already been called by someone else; it can only be called one time.
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:12:13
    at /usr/local/lib/node_modules/@petro-kushchak/homebridge-homepod-radio/src/lib/homebridgeCallbacks.ts:19:34
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Updating python, node, ffmpeg
No change in behaviour

**Comment by petro-kushchak** [comment]
Hi, I've re-implemented the way plugin streams audio to HomePod, "beta" version runs for a couple of months already, and its pretty stable in my setup (will prepare release with this version pretty soon)

Try out this version: @petro-kushchak/homebridge-homepod-radio v1.2.16-beta.5 

It also allows to add "switch" accessory, so you can turn on/off radio

**Comment by tomasfearon** [comment]
I've tried v1.2.16-beta.5 several times without success. The switch doesn't allow you to turn off the stream once it crashes Homebridge, even when Homebridge restarts. 

If you would prefer, I can close this issue with v1.1.41 and open a new one with more detailed information and errors for v1.2.16-beta.5.

**Comment by petro-kushchak** [comment]
Hi, could you please share plugin configuration and logs?

**Comment by tomasfearon** [comment]
Cleaned up some possibly conflicting Python versions and now v1.2.16-beta.5 seems to be working smoothly. I'll monitor and create another issue if any arise, thanks!
