### ISSUE TITLE
Playing MP3 ok, but volume issue

### ISSUE THREAD

**Issue by johnnygoodface** [petro-kushchak/homebridge-homepod-radio#31]
Hi,
When I play my .mp3 file with http://192.168.1.28:7654/play/Sunshine.mp3 it plays at 100% of volume on my Airport Express with speakers. But when I play the .mp3 a second time (and the same thereafter) the sound is only about 40% loud.
Even if I restart Homebridge the sound is still at 40%
Any idea?

**Comment by petro-kushchak** [comment]
Hi - this is strange, plugin just invokes command

`atvremote --id ${homepodId} stream_file=${filePath}`

w/o specifying volume level...

I could add some "default" volume setting, which would be used when playing files

**Comment by johnnygoodface** [comment]
Don't mind me, but if you could I'd be glad to test it out 
Thx

**Comment by petro-kushchak** [comment]
Hi, try beta version of homebridge-homepod-radio-2.0.9 with audio switch accessory and volume control :)
