### ISSUE TITLE
Some suggestions for improvement

### ISSUE THREAD

**Issue by postlund** [petro-kushchak/homebridge-homepod-radio#36]
Just wanted to let you know that it's possible to pass custom metadata when streaming now (so you don't have to patch internals of pyatv to do that). The documentation is here:

https://pyatv.dev/development/stream/#custom-metadata

I also suggest that you run ffmpeg the way I'm doing here (to stay in asyncio land):

https://pyatv.dev/development/stream/#stream-a-file

**Comment by petro-kushchak** [comment]
Thanks, @postlund  - will migrate to latest pyatv!

**Comment by postlund** [comment]
Great! I'm gonna extend the custom metadata support with an "override missing" flag as well (I'll start working on it now). It will allow you to use the metadata provided from a file or (radio) stream if present, but fall back to static metadata in case no metadata exists or extraction fail. So hopefully you will be able to present correct radio metadata. I'll see if I can work on artwork later as well.

**Comment by postlund** [comment]
I added support for artwork and made it possible to only override metadata in case it's not present in the stream. Everything is part of the 0.13.2 release.
