### ISSUE TITLE
Update from 2.0.9 to 3.0.x

### ISSUE THREAD

**Issue by Matt-Eagle-Pi** [petro-kushchak/homebridge-homepod-radio#40]
Hi @petro-kushchak! 

I've tried the Update to every Version 3.0.x. After that, I can't activate any radio over HomeKit anymore. Do I have to reset all previous settings? 

Greetings,
Matt

PS: pyatv and node.js are up to date.

**Comment by petro-kushchak** [comment]
Hi, try to add switch accessories again. If it doesn't help - please share homebridge logs

**Comment by Matt-Eagle-Pi** [comment]
Hi @petro-kushchak. Now I tried it wie Version 3.0.0. The log Shows the error: 

[18.10.2023, 21:07:06] [petro-kushchak/homebridge-homepod-radio] [JazzRadio Berlin ]
Error while trying to stop: Error: Command failed: kill -9 11149
/bin/sh: 1: kill: No such process

I have the Same issues with the Audio Buttons...

Matt

**Comment by petro-kushchak** [comment]
In case if you still try 3.+ could you please enable verbose mode ("verbose": true in plugin config) and send logs again?

Most probably it's related to user/permissions which are used to access pyatv package from homebridge...

**Comment by petro-kushchak** [comment]
It was reported by others as well, try to install pyatv from homebridge terminal - looks like somehow latest pyatv is not accessible for linux user which runs homebridge

**Comment by Matt-Eagle-Pi** [comment]
Thanks. I'll try it.

**Comment by Matt-Eagle-Pi** [comment]
Hi. Just installed pyatv via Homebridge-Terminal. Doesn't worked for me. Andy hint?

**Comment by petro-kushchak** [comment]
Hi - try steps from this issue: https://github.com/petro-kushchak/homebridge-homepod-radio/issues/35#issuecomment-1481018025

**Comment by Matt-Eagle-Pi** [comment]
Hi. 

Does't work for my installation. Now I installed pyatv with "sudo -H pip3 install pyatv" again.  The same log as before. Homebridge is now installed under user pi and user homebridge.  Under Root-User Pi, I get a warning,:

WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

Maybe thats the problem...

I really miss the function to change music volume in Homekit but I will reinstall the version 2.0.9.

Nevertheless, thanks for your support so far!

**Comment by Matt-Eagle-Pi** [comment]
Hi @petro-kushchak.

As offered, I installed pyatv under Root with sudo -H pip3 install pyatv and Updates Thema the Plugin to Version 3.0.

Now I get the following log:

![image](https://github.com/petro-kushchak/homebridge-homepod-radio/assets/122724916/90778c76-453f-4e16-8cc1-56c281abcc08)

**Comment by Matt-Eagle-Pi** [comment]
Update:

After installing everything again, the error is the same, as before:

![image](https://github.com/petro-kushchak/homebridge-homepod-radio/assets/122724916/80098904-84ae-4d63-8a77-0865f42a403b)

I installed the Homebridge manually on a pi-debian to run zigbee2mqtt side by side on the same system. 

Maybe you have another idea, I can check in my system...

Thanks, Matt

**Comment by petro-kushchak** [comment]
Hi, can you check which version of python3 you have? Now I remember that I had to upgrade python to 3.10 to be able to install proper version of pyatv...

**Comment by petro-kushchak** [comment]
Actually from screenshot I see that you have python 3.7, please upgrade to 3.9-3.10

**Comment by Matt-Eagle-Pi** [comment]
Hi. Thanks for the hint. Now I have installed Python 3.10.

![image](https://github.com/petro-kushchak/homebridge-homepod-radio/assets/122724916/fbf528a6-f573-4c03-8e26-b7170d85d182)

But the Plugin still uses the Python 3.7 Installation:

![image](https://github.com/petro-kushchak/homebridge-homepod-radio/assets/122724916/4571b458-dc95-41e4-b37a-988f14cba700)


Now do I change this? Plugin reinstall? 

Hopefully not...

**Comment by petro-kushchak** [comment]
No, I think you should change default version of python3 globally. One of the options:

```
sudo rm /usr/bin/python3
sudo ln -s /usr/bin/python3.10 /usr/bin/python3
```

**Note**: before running check that  `/usr/bin/python3.10` exists (in my case its located in `/usr/local/bin/python3.10`) and that `python3` is executed from `/usr/bin/python3` (run `which python3`)

**Comment by Matt-Eagle-Pi** [comment]
Thanks. This works. Now the Erker turned to this:

![image](https://github.com/petro-kushchak/homebridge-homepod-radio/assets/122724916/9a57e717-ed87-49f0-bd4f-c525dd53b7e0)

**Comment by petro-kushchak** [comment]
Check that link to python3 works properly, from error looks like python3 command doesn't work

**Comment by Matt-Eagle-Pi** [comment]
Hello Petro. I just updated my Raspberry to Raspbian Bookworm (64-bit) and installed your plugin in Version 3.0.  The volume-switch is available and music-streaming works great. 

But the button-playback doesn't work. Do you know about that?

Regards, 
Matt

**Comment by petro-kushchak** [comment]
Hi, can you attach some logs? Sounds like some configuration issue

**Comment by Matt-Eagle-Pi** [comment]
Hi Petro. Here is the log. Pyatv is installed in a virtual-environment under homebridge. The permission of the media-path is set to 777. I hope you can find the issue. Thanks in advance! 

Matt

**Comment by petro-kushchak** [comment]
hi @Matt-Eagle-Pi  - from logs I see that it can not decode file:

[15.11.2024, 10:25:52] [@petro-kushchak/homebridge-homepod-radio] [Postbox] streaming data:     raise DecodeError("failed to decode file", result)
miniaudio.DecodeError: ('failed to decode file', -6)

maybe file which you are trying to stream somehow broken?

**Comment by Matt-Eagle-Pi** [comment]
Hi. No, same error with another file...

**Comment by petro-kushchak** [comment]
looks like something wrong with command parameters, try:

`atvremote --id <homepod-id> stream_file=/home/homebridge/media/mail.mp3`

**Comment by Matt-Eagle-Pi** [comment]
Hi Petro. Thanks for the hint. Now we get closer.  Here is the new log:

[homebridge.log.txt](https://github.com/user-attachments/files/17834525/homebridge.log.txt)
