### ISSUE TITLE
HomePod & Volume accessories created even if not configured

### ISSUE THREAD

**Issue by aboulfad** [petro-kushchak/homebridge-homepod-radio#41]
Hi,

I use your great plugin to play announcements on my HomePod minis using http get method (shortcuts), as such I don't configure radios or audioFiles section in my config. Even there's no config entries, the plugin (I believe) creates HomeKit accessories that show up when adding other accessories.

In my config, I have 3 separate platforms with separate bridge username/port entries (for 3 HomePod minis), in my HK add accessory I end up w 6 un-needed/un-used accessories (3x HomePod radio, 3x Volume).

Would it be possible to only create those HK acc if they are configured ? Thanks.

Example from my config:
```
        {
            "homepodId": "idA",
            "serialNumber": "snA",
            "mediaPath": "/home/pi/media",
            "httpPort": 1234,
            "enableVolumeControl": false,
            "verboseMode": false,
            "_bridge": {
                "username": "DE:AD:BE:EF:DE:AD",
                "port": 33333
            },
            "platform": "HomepodRadioPlatform"
        }
```

**Comment by petro-kushchak** [comment]
Hi, @aboulfad - that's strange, will investigate...

**Comment by aboulfad** [comment]
Thank you, plz lmk if you need any logs or additional data.

**Comment by petro-kushchak** [comment]
Hi - could you please provide more logs, I've double checked the code and it should not create any accessories unless these are specified in the config...

**Comment by aboulfad** [comment]
Hi, here's some additional logs after restarting HB. I can further enable -D & collect those verbose logs. I have replaced some "sensitive" info (ports, Mac address,...) in both files. Those 3 volume acc + radio acc do show up in HomeKit when trying to add a new accessory. I have tried deleting them in HB "Unpair Bridges / Cameras / TVs / External Accessories" but they come back.

[homebridge.log.txt](https://github.com/petro-kushchak/homebridge-homepod-radio/files/13403092/homebridge.log.txt)
[config-hp.json](https://github.com/petro-kushchak/homebridge-homepod-radio/files/13403093/config-hp.json)

**Comment by aboulfad** [comment]
Could this be the culprit ? https://github.com/petro-kushchak/homebridge-homepod-radio/blob/884851e65309d4075e267b4e375b557078d0ca67/src/platformConfig.ts#L68

**Comment by petro-kushchak** [comment]
yes, looks like this is backward compatibility issue - its not needed anymore, will release new version shortly

**Comment by petro-kushchak** [comment]
could you please try to install this alpha version: `@petro-kushchak/homebridge-homepod-radio v3.0.5`

Should have this issue fixed

**Comment by aboulfad** [comment]
can you please 😄 post the code in GH (commit, tag, branch) ? I have a local install of your plugin that I modified and is rubbing so I'd need to merge your changes to test them.

**Comment by petro-kushchak** [comment]
yep, this is the commit:
https://github.com/petro-kushchak/homebridge-homepod-radio/commit/4a1492dfac56c79f0fe447f8b8dd8ef23e4198eb

**Comment by aboulfad** [comment]
Thanks for the commit, I cherry-picked it and the Radio acc doesn't get created, great ! but we still have the Volume acc that are being created although not configured. I couldn't fully figure it out, but this code https://github.com/petro-kushchak/homebridge-homepod-radio/blob/884851e65309d4075e267b4e375b557078d0ca67/src/platform.ts#L70 should run & return & have a log entry which I can't find.

**Comment by petro-kushchak** [comment]
@aboulfad - good point! Changing it to `false` by default - this plugin got too many config entries, getting hard to test everything :)

**Comment by aboulfad** [comment]
The pseudo code could be as follows:
1- If a config entry exists, read it
2- If no config entry exists, set the default to false

I don’t understand why that line doesn’t work but the following works based on the above pseudo code:

this.enableVolumeControl = config.enableVolumeControl;
If (this.enableVolumeControl === undefined) {
    this.enableVolumeControl = false;
}

Oh gosh after staring at it for some time I get it, enableVolumeControl is a **Boolean**, if the config value is false and it’s or’ed ( || )with true, the result will ALWAYS be true!!!

**Comment by petro-kushchak** [comment]
correct, so make sense to default it to `false`... in your case you can even comment out piece which adds volume control accessory (comment out `this.addHomepodVolumeAccessory()` inside `platform.ts`)

**Comment by aboulfad** [comment]
Thanks, I added my above code that handles correctly the boolean config value. This way I can still enable a vol acc in the future. Closing this issue, thanks for your support : )
