### ISSUE TITLE
IOS 18 beta

### ISSUE THREAD

**Issue by leendersf** [petro-kushchak/homebridge-homepod-radio#50]
FYI: my Homepods are on IOS 18 but none of the versions seem to work after the update.

**Comment by petro-kushchak** [comment]
Hi, looks like pyatv is not compatible yet:  https://github.com/postlund/pyatv/issues/2403

**Comment by leendersf** [comment]
Thank you! I think you are right!

**Comment by leendersf** [comment]
[@petro-kushchak_homebridge-homepod-radio.log.txt](https://github.com/user-attachments/files/16321245/%40petro-kushchak_homebridge-homepod-radio.log.txt)

Here you go!

**Comment by jiggyjigsj** [comment]
Interestingly enough, my HomePod mini stopped working a few days ago.  When i ran `atvremote scan`, i noticed all the mac addresses changed.  Once i changed the config with new mac addresses and triggered a playback, it worked fine.   I wonder if apple pushed the random mac addresses to HomePods now. 

<img width="486" alt="image" src="https://github.com/user-attachments/assets/39de6400-4e71-41a6-983f-a18cb64af70a">

**Comment by leendersf** [comment]
Yes this is the solution!!! Thank you!!!

**Comment by petro-kushchak** [comment]
Also started failing for me with latest iOS 18 beta:


[ios18-homepod-pyatv-logs.txt](https://github.com/user-attachments/files/16595461/ios18-homepod-pyatv-logs.txt)

**Comment by leendersf** [comment]
Here everything playing fine: latest beta.

**Comment by jiggyjigsj** [comment]
I am currently not home and should return tomorrow. I can check my logs to see if I see similar errors. Looking at the errors logs, looks like it timed out or the "server - device triggered a disconnect". 

I can try to replicate the issues on my side when I am back home.

Did you trigger the playback off of home bridge or a button simulation?

**Comment by petro-kushchak** [comment]
seems to work fine with latest iOS/tvOs
