### ISSUE TITLE
Multi radio not show in Home app

### ISSUE THREAD

**Issue by napo-leon** [petro-kushchak/homebridge-homepod-radio#7]
Hello,

First of all big thanks for your work!!
But I have one issue, I have well configure your plugins with multi radio but only the first radio is show in my home app.
This button work well but why the other one are hide?

Also I have a request: I would like to start this button radio via siri. It's possible? If not, possible to have a switch to on off radio to be trigger in homekit?

Thanks!!!

>         {
>             "homepodId": "XX:D3:XX:0D:XX:F5",
>             "serialNumber": "HXXXXXXXXXXJ",
>             "verboseModel": false,
>             "volumeControl": false,
>             "radios": [
>                 {
>                     "name": "France info",
>                     "radioUrl": "http://direct.franceinfo.fr/live/franceinfo-midfi.mp3",
>                     "volume": 25,
>                     "autoResume": false
>                 },
>                 {
>                     "name": "France inter",
>                     "radioUrl": "http://direct.franceinter.fr/live/franceinter-midfi.mp3",
>                     "volume": 25,
>                     "autoResume": false
>                 },
>                 {
>                     "name": "RMC",
>                     "radioUrl": "http://rmc.bfmtv.com/rmcinfo-mp3",
>                     "autoResume": false
>                 }
>             ],
>             "platform": "HomepodRadioPlatform"
>         },

**Comment by petro-kushchak** [comment]
Hi,

With iOS 15 you have to add each speaker accessory separately (and re-enter homebridge pin)

Regarding starting radio with Siri - I've created shortcut named "Start Radio" (just select "Control home" action, check corresponding speaker and in "Media" section select "Resume Audio"). Then "Hey Siri, start radio" works on iPhone/iPad, but on HomePod mini Siri does not run it properly. Your suggestion with switch should fix this issue - will take a look how to combine speaker and switch per "radio"

Thanks for your feedback, will update readme :)

**Comment by napo-leon** [comment]
Thanks for your feedback!!
